version: '3.3'
services:
  php:
    build: .
    container_name: php-server
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/html
    links:
    - db

  db:
    container_name: db
    image: mysql:5.7
    volumes:
    - /var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=php_db